### ISSUE TITLE
Issue with Clipboard Copy Functionality

### ISSUE THREAD

**Issue by sorooshsorkhani** [roboflow/polygonzone#2]
### Search before asking

- [X] I have searched the PolygonZone [issues](https://github.com/roboflow/polygonzone/issues) and found no similar bug report.

### Bug

I encountered an issue with the clipboard copy functionality in your online tool. When clicking on the `Copy Python to Clipboard` button, instead of copying the Python code, it seems to be copying the text "Copy Python to Clipboard"

### Environment

Browser: Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wpchen** [comment]
+1 to this issue.

**Comment by capjamesg** [comment]
This issue has been fixed in #14 and merged. Let us know if the issue persists.
